// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"time"
)

type Query struct {
}

type Transaction struct {
	ID     int       `json:"id"`
	Date   time.Time `json:"date"`
	Amount float64   `json:"amount"`
}

type Yield struct {
	ID     int       `json:"id"`
	Date   time.Time `json:"date"`
	Amount float64   `json:"amount"`
}
