// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameBifrostStakingTable = "Bifrost_staking_table"

// BifrostStakingTable mapped from table <Bifrost_staking_table>
type BifrostStakingTable struct {
	ID              int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BatchID         int32      `gorm:"column:batch_id;not null" json:"batch_id"`
	ContractAddress *string    `gorm:"column:contractAddress" json:"contractAddress"`
	Symbol          *string    `gorm:"column:symbol" json:"symbol"`
	Slug            *string    `gorm:"column:slug" json:"slug"`
	BaseSlug        *string    `gorm:"column:baseSlug" json:"baseSlug"`
	UnstakingTime   *int32     `gorm:"column:unstakingTime" json:"unstakingTime"`
	Users           *int32     `gorm:"column:users" json:"users"`
	Apr             *float64   `gorm:"column:apr" json:"apr"`
	Fee             *float64   `gorm:"column:fee" json:"fee"`
	Price           *float64   `gorm:"column:price" json:"price"`
	ExchangeRatio   *float64   `gorm:"column:exchangeRatio" json:"exchangeRatio"`
	Supply          *float64   `gorm:"column:supply" json:"supply"`
	CreatedAt       *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName BifrostStakingTable's table name
func (*BifrostStakingTable) TableName() string {
	return TableNameBifrostStakingTable
}
