// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameBifrostBatchIDTable = "Bifrost_batchID_table"

// BifrostBatchIDTable mapped from table <Bifrost_batchID_table>
type BifrostBatchIDTable struct {
	ID        int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BatchID   int32      `gorm:"column:batch_id;not null" json:"batch_id"`
	Chain     *string    `gorm:"column:chain" json:"chain"`
	Status    *string    `gorm:"column:status" json:"status"`
	CreatedAt *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName BifrostBatchIDTable's table name
func (*BifrostBatchIDTable) TableName() string {
	return TableNameBifrostBatchIDTable
}
