// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameBifrostSiteTable = "Bifrost_site_table"

// BifrostSiteTable mapped from table <Bifrost_site_table>
type BifrostSiteTable struct {
	AutoID                   int32      `gorm:"column:auto_id;primaryKey;autoIncrement:true" json:"auto_id"`
	BatchID                  int32      `gorm:"column:batch_id;not null" json:"batch_id"`
	Asset                    *string    `gorm:"column:Asset" json:"Asset"`
	Value                    *float64   `gorm:"column:Value" json:"Value"`
	Tvl                      *float64   `gorm:"column:tvl" json:"tvl"`
	Tvm                      *float64   `gorm:"column:tvm" json:"tvm"`
	Holders                  *int32     `gorm:"column:holders" json:"holders"`
	Apy                      *float64   `gorm:"column:apy" json:"apy"`
	ApyBase                  *float64   `gorm:"column:apyBase" json:"apyBase"`
	ApyReward                *float64   `gorm:"column:apyReward" json:"apyReward"`
	TotalIssuance            *float64   `gorm:"column:totalIssuance" json:"totalIssuance"`
	HoldersList              *string    `gorm:"column:holdersList" json:"holdersList"`
	AnnualizedIncome         *float64   `gorm:"column:annualized_income" json:"annualized_income"`
	BifrostStaking7dayApy    *float64   `gorm:"column:bifrost_staking_7day_apy" json:"bifrost_staking_7day_apy"`
	Created                  *time.Time `gorm:"column:created" json:"created"`
	DailyReward              *float64   `gorm:"column:daily_reward" json:"daily_reward"`
	ExitedNode               *int32     `gorm:"column:exited_node" json:"exited_node"`
	ExitedNotTransferredNode *int32     `gorm:"column:exited_not_transferred_node" json:"exited_not_transferred_node"`
	ExitingOnlineNode        *int32     `gorm:"column:exiting_online_node" json:"exiting_online_node"`
	GasFeeIncome1            *float64   `gorm:"column:gas_fee_income" json:"gas_fee_income"`
	ID                       *int32     `gorm:"column:id" json:"id"`
	Mev7dayApy               *float64   `gorm:"column:mev_7day_apy" json:"mev_7day_apy"`
	MevApy1                  *float64   `gorm:"column:mev_apy" json:"mev_apy"`
	MevIncome1               *float64   `gorm:"column:mev_income" json:"mev_income"`
	OnlineNode               *int32     `gorm:"column:online_node" json:"online_node"`
	SlashBalance             *float64   `gorm:"column:slash_balance" json:"slash_balance"`
	SlashNum                 *int32     `gorm:"column:slash_num" json:"slash_num"`
	StakingApy1              *float64   `gorm:"column:staking_apy" json:"staking_apy"`
	StakingIncome1           *float64   `gorm:"column:staking_income" json:"staking_income"`
	TotalApy1                *float64   `gorm:"column:total_apy" json:"total_apy"`
	TotalBalance             *float64   `gorm:"column:total_balance" json:"total_balance"`
	TotalEffectiveBalance    *float64   `gorm:"column:total_effective_balance" json:"total_effective_balance"`
	TotalNode                *int32     `gorm:"column:total_node" json:"total_node"`
	TotalReward              *float64   `gorm:"column:total_reward" json:"total_reward"`
	TotalWithdrawals         *float64   `gorm:"column:total_withdrawals" json:"total_withdrawals"`
	StakingApy               *float64   `gorm:"column:stakingApy" json:"stakingApy"`
	StakingIncome            *float64   `gorm:"column:stakingIncome" json:"stakingIncome"`
	MevApy                   *float64   `gorm:"column:mevApy" json:"mevApy"`
	MevIncome                *float64   `gorm:"column:mevIncome" json:"mevIncome"`
	GasFeeApy                *float64   `gorm:"column:gasFeeApy" json:"gasFeeApy"`
	GasFeeIncome             *float64   `gorm:"column:gasFeeIncome" json:"gasFeeIncome"`
	TotalApy                 *float64   `gorm:"column:totalApy" json:"totalApy"`
	TotalIncome              *float64   `gorm:"column:totalIncome" json:"totalIncome"`
	BaseApy                  *float64   `gorm:"column:baseApy" json:"baseApy"`
	FarmingAPY               *float64   `gorm:"column:farmingAPY" json:"farmingAPY"`
	Veth2TVS                 *float64   `gorm:"column:veth2TVS" json:"veth2TVS"`
	ApyMev                   *float64   `gorm:"column:apyMev" json:"apyMev"`
	ApyGas                   *float64   `gorm:"column:apyGas" json:"apyGas"`
	CreatedAt                *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName BifrostSiteTable's table name
func (*BifrostSiteTable) TableName() string {
	return TableNameBifrostSiteTable
}
