// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbgen

import (
	"time"
)

const TableNameFullTable = "full_table"

// FullTable mapped from table <full_table>
type FullTable struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Source     string     `gorm:"column:source;not null" json:"source"`
	Chain      string     `gorm:"column:chain;not null" json:"chain"`
	BatchID    *int64     `gorm:"column:batch_id" json:"batch_id"`
	Symbol     *string    `gorm:"column:symbol" json:"symbol"`
	FarmApy    *float64   `gorm:"column:farm_apy" json:"farm_apy"`
	PoolApy    *float64   `gorm:"column:pool_apy" json:"pool_apy"`
	Apy        *float64   `gorm:"column:apy" json:"apy"`
	Tvl        *float64   `gorm:"column:tvl" json:"tvl"`
	Volume     *float64   `gorm:"column:volume" json:"volume"`
	Tx         *int64     `gorm:"column:tx" json:"tx"`
	Price      *float64   `gorm:"column:price" json:"price"`
	CreatedAt  *time.Time `gorm:"column:created_at" json:"created_at"`
	InsertedAt *time.Time `gorm:"column:inserted_at;default:CURRENT_TIMESTAMP" json:"inserted_at"`
}

// TableName FullTable's table name
func (*FullTable) TableName() string {
	return TableNameFullTable
}
