// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbgen

import (
	"time"
)

const TableNameMultipleYield = "multiple_yields"

// MultipleYield mapped from table <multiple_yields>
type MultipleYield struct {
	ID          int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BatchID     int32      `gorm:"column:batch_id;not null" json:"batch_id"`
	TokenSymbol *string    `gorm:"column:token_symbol" json:"token_symbol"`
	Chain       *string    `gorm:"column:chain" json:"chain"`
	Tvl         *float64   `gorm:"column:tvl" json:"tvl"`
	Yield       *string    `gorm:"column:yield" json:"yield"`
	Price       *float64   `gorm:"column:price" json:"price"`
	Vols24      *float64   `gorm:"column:vols_24" json:"vols_24"`
	Txns24      *float64   `gorm:"column:txns_24" json:"txns_24"`
	AssetType   *int32     `gorm:"column:asset_type" json:"asset_type"`
	CreatedAt   *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName MultipleYield's table name
func (*MultipleYield) TableName() string {
	return TableNameMultipleYield
}
