// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbgen

const TableNameTokenExt = "token_ext"

// TokenExt Table to store extended token information
type TokenExt struct {
	Chain      string  `gorm:"column:chain;primaryKey;comment:Chain Name" json:"chain"`   // Chain Name
	Token      string  `gorm:"column:token;primaryKey;comment:Primary Key" json:"token"`  // Primary Key
	Type       *string `gorm:"column:type;comment:Asset Type" json:"type"`                // Asset Type
	ReturnType *string `gorm:"column:return_type;comment:Return Type" json:"return_type"` // Return Type
}

// TableName TokenExt's table name
func (*TokenExt) TableName() string {
	return TableNameTokenExt
}
